### ISSUE TITLE
Clarification for \usepackage[T1]{fontenc}

### ISSUE THREAD

**Issue by CptPie** [fs-wiai/LaTeX-Tutorial#3]
For reference https://tex.stackexchange.com/questions/664/why-should-i-use-usepackaget1fontenc
Tl:dr
* Without T1 it will not be possible to use commands like /accent and get the expected result
* Copy and pasting wont work properly

**Comment by muellermartin** [comment]
Thanks for pointing that out explicitly. Because of this we consider switching to Xe(La)TeX in the near future which enables to use "normal" TTF fonts and alike with native UTF-8 encoding (also no additional package needed) so this annoying issue should be gone.

**Comment by CptPie** [comment]
Well its not exactly an issue - possible problems with Xe(La)TeX as far as i have read might have problems with some usually used packages from LaTeX

**Comment by muellermartin** [comment]
Yep, that's one concern which we also have, but in most cases there are replacement packages available, e.g. `polyglossia` instead of `babel` which work exactly the same (or even better).

**Comment by LinusDietz** [comment]
I would discourage to teach xelatex by default, because the compiler is soo slow, and the advantages are really minor for a beginner user...

**Comment by muellermartin** [comment]
Hm, I'd state the exact opposite, because the already mentioned native UTF-8 support and better font encoding (TTF & OTF) alone are reasons to switch. Beginners don't get why inserting Umlauts, or established symbols (€, typographically correct quotation marks like „” «» etc. require escape sequences/commands or even dedicated packages). The usage of system fonts (TTF & OTF) is dead simple as it should be and T1 encoded fonts also suffer from Font-Kerning issues (we even have this issue in our own slides). In my eyes these features overcome the increased compile time. Advanced users who prefer speed over ease of use still can switch back to LaTeX.
